#Native Android project
workflows:
    android-app: # workflow ID
        name: Android app # workflow name
        scripts:
            - chmod +x ./gradlew
            - ./gradlew assembleDebug
        artifacts:
            - build/outputs/**/**/*.apk
